---
openapi: 3.0.3
info:
  title: String converter
  description: |-
    This service performs basic string conversions.
  version: 1.0.0
tags:
  - name: strings
    description: Basic string operations.
paths:
  /upper:
    get:
      tags:
        - string
      summary: Convert to uppercase.
      description: Converts a string to uppercase.
      operationId: upper
      parameters:
        - name: text
          in: query
          required: true
          schema:
            type: string
          example: hello
      responses:
        '200':
          description: Successful operation.
          content:
            text/plain:
              schema:
                type: string
              example: hello
