
name: Run unit test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: "23"
      - name: unit test
        run: bash ./gradlew test
      - name: unit test results
        uses: actions/upload-artifact@v1
        with:
          name: unit-test-results
          path: ./app
          